name = "Bijectors"
uuid = "76274a88-744f-5084-9051-94815aaf08c4"
version = "0.5.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Distributions = "0.21.11, 0.22"
ForwardDiff = "0.10.3"
MappedArrays = "0.2.2"
NNlib = "0.6"
Reexport = "0.2"
Requires = "1"
Roots = "0.8.4"
StatsFuns = "0.8, 0.9.3"
Tracker = "0.2.3"
julia = "1"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"

[targets]
test = ["ForwardDiff", "Test", "Tracker"]
